title: Our Final Project is Really Just for Karma. Sorry. 
logo: /assets/img/logo.png
description: Final Project for MUSA 550 Geospatial Data Science in Python.
show_downloads: false
repository: bri-ne/KarmaMine
google_analytics:
remote_theme: pages-themes/minimal
plugins:
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include: 
  - Proposal.md
  - Results.md